### PR TITLE
Fix getProjectPaths refers wrong path

### PR DESCRIPTION
**Pull request by imazine**
Fix subtle issues #280

### CODE REVIEW

**Comment by bchatard** [comment]
Hi,

Thanks for your contribution!

This backup folder is something managed by JetBrains when upgrading?

**Comment by imazine** [comment]
@bchatard I guess that backup folders made when upgrade using Jetbrains Toolbox

**Comment by imazine** [comment]
I guess that backup folders did not using for upgrade And I upgrade all things by `Jetbrains Toolbox` 
Here is my `PreferencePath` 

image

**Comment by bchatard** [comment]
ok weird I don't have it

I'll merge your work, and I'll release new version asap

**Pull request merged**
