### PR TITLE
Add toolbox script path to environment path

### LINKED ISSUE #294: Unable to find bin for ${product.key}. Search for bin named
### FAQ

- [X] Yes, my issue is not listed in [troubleshooting guide](https://github.com/bchatard/alfred-jetbrains/blob/main/doc/troubleshooting.md).
- [X] Yes, my issue is not listed in other issues.

### Describe the bug

 When search list of projects with the product keyword the error occurred
 

### To Reproduce

1. Open alfred search box
2. Project search by product name
3. Error occurred

### Expected behavior

Error caused by wrong environment variable `PATH`. I had print out `PATH` variable with console and I got another value that is not same with command line.

### Alfred Version

Alfred 5.0.6

### Node Version

v18.3.0

### NPM Version

8.15.0

### Jetbrains Product & Version

JetBrains Toolbox 1.27.2.13801

### Installation type

Homebrew

### OS

macOS 13.1

### PR DESCRIPTION
**Pull request by imazine**
Append toolbox script path to PATH variable
This commit for fix  #294

### CODE REVIEW

**Comment by bchatard** [comment]
Hi,

where are located your JetBrains binaries? In `${process.env.HOME}/Library/Application Support/JetBrains/Toolbox/scripts`?

Per default it's `/usr/local/bin` and this path is available to `$PATH` with no additional configuration

**Comment by imazine** [comment]
@bchatard I am a `Jetbrain Toolbox` user and my binaries located in  `~/Library/Application Support/Jetbrain/Toolbox/scripts` It is default shell script location of toolbox. I suggest two solution for this issue. First is add a default script path(like this PR) and the other is add subtle guide for set a default shell script location to system default (e.g. `/usr/loal/bin` but It need to root permission)
image

image

**Comment by bchatard** [comment]
Same for me, I'm using Toolbox since the beginning and scripts are still localized in ˋ/usr/local/binˋ. Maybe a change in fresh toolbox install.
Anyway, did the script can be run in your terminal?
Maybe you should add the path to your ˋ$PATHˋ in your ˋ~/.zshrcˋ.

**Comment by imazine** [comment]
@bchatard I guess your `/usr/local/bin` permission is not same with OS default(It is not writable without root permission). and I tried to change $PATH  in my `.zshrc` configuration but It did not works. 

image

**Comment by imazine** [comment]
@bchatard I can't find any reference about `/usr/local/[sub_directories]` changed to writable. If it was available then any application with user permission can change other binaries under the location. I guess your path was changed by yourself.

**Comment by bchatard** [comment]
Hi @GertVil 

since the bin doesn't work in your terminal, the issue is not related to this workflow

**Comment by GertVil** [comment]
Hey @bchatard 

You might have misread my original message, using `idea` in the terminal does in fact work 
```
➜  /tmp mkdir test-project
➜  /tmp cd test-project
➜  test-project which idea
/Users/gert/Library/Application Support/JetBrains/Toolbox/scripts/idea
➜  test-project idea .
➜  test-project
```
and Intellij opens inside the test-project dir. 
I applied this MR locally, and it fixes the workflow.
Default settings are the same as @imazine 's 
image

**Comment by bchatard** [comment]
Oups sorry

Can you try to echo your $PATH in Alfred script filter?

image


image

**Comment by GertVil** [comment]
Yeah as per https://www.alfredapp.com/help/workflows/advanced/understanding-scripting-environment/ they differ my PATH in normal shell includes the `/Users/gert/Library/Application Support/JetBrains/Toolbox/scripts` and the echo in the script filter does not contain `/Users/gert/Library/Application Support/JetBrains/Toolbox/scripts`.
Do you have objects to merging this PR? Because it would probably solve the issue for a lot of people without them having to adjust the path before the script runs.
Since this is the new default location toolbox uses I'm guessing the problem will arise more and more.

**Comment by bchatard** [comment]
nice catch @GertVil 

as a workaround I'll merge this

**Pull request merged**
